name = "sweet-math-b87f"       # Cloudflare Worker 名称
type = "javascript"            # 项目类型: "javascript"、"webpack"、"module"
main = "index.js"              # 入口文件（可选）

compatibility_date = "2025-08-06"  # Cloudflare 要求的版本兼容日期

