name = "sweet-math-b87f"       # Cloudflare Worker 名称
type = "javascript"            # 项目类型: "javascript"、"webpack"、"module"
main = "index.js"              # 入口文件（可选）

compatibility_date = "2025-08-06"  # Cloudflare 要求的版本兼容日期

# 可选项：
account_id = "你的 Cloudflare 账号 ID"
workers_dev = true                  # 使用 Workers Dev 子域部署（开发模式）
